### ISSUE TITLE
Wrong ACL lookup in traversal

### ISSUE THREAD

**Issue by asif-mahmud** [Pylons/pyramid#2983] opened 2017-03-25 22:12 UTC
Hi,
Say i have a resource tree like this -
```
class Root(object):
    def __getitem__(self, item):
        if item == 'a':
            return A()
    def __acl__(self):
        return [(Allow, Everyone, ALL_PERMISSIONS)]

class A(object):
    def __acl__(self):
        return [(Allow, Everyone, 'view')]
```

Now i have a view class like this while default renderer is JSON renderer-
```
@view_defaults(context=A)
class AView(object):
    def __init__(self, request):
        self.request = request
    @view_config(name='b', permission='edit')
    def edit(self):
        return dict(status='OK')
```
Now if i run the application and run the following command -

`curl -i http://localhost:8080/a/b`

I get the following result (headers excluded) -
```
{"status":"OK"}
```
Why am I getting this response ? Shouldn't it be denied by `ACLAuthorizationPolicy` ?

I checked further with authorization debugging turned on. I found a surprising fact that the `ACE` for the view named a `b` isn't checked against the `A` context, instead it was checking against `Root` Context where `Everyone` has `ALL_PERMISSIONS` allowed.

Another surprising fact is class `A` is still the context for view `b`.

Is this normal ? If it is please explain what's happening here.

Thanks -
Asif Mahmud Shimon

**Comment by mmerickel** [comment] 2017-03-25 22:25
This example isn't complete enough for me to answer your question. Perhaps you can paste a reproducible single file example containing your configuration directives as well. A skeleton you can fill in is below:

```python
from pyramid.config import Configurator

def main(global_config, **settings):
    config = Configurator(settings=settings)
    config.scan(__name__)
    return config.make_wsgi_app()

if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    app = main({})
    server = make_server('0.0.0.0', 8080, app)
    server.serve_forever()
```

**Comment by stevepiercy** [comment] 2017-03-25 22:48
@asif-mahmud GitHub issue trackers are primarily intended to report issues and bugs with Pyramid (and other Pylons Project projects) core code and documentation.

To reach a wider audience than the handful of developers who subscribe to GitHub issue tracker notifications, you can send your request to the mail list or IRC channel, per our guidelines:
http://pylonsproject.org/community-support.html

As a side note, I think we can improve how we direct users to get the appropriate support on our websites. @asif-mahmud what led you to both (1) send an email to pylons-project-security@googlegroups.com and (2) post your request for support on the issue tracker? I'm currently revising content on our websites (pylonsproject.org and trypyramid.com, as well as documentation) to make things consistent and clear to visitors. Thank you!

**Comment by stevepiercy** [comment] 2017-03-26 21:43
Closing. @asif-mahmud replied to pylons-project-security@googlegroups.com:

```
Hi,
Turned out I made a terrible mistake about designing ACEs. Now it's working
as expected.
Thank you very much for such quick response.
```

I've also revised text on PylonsProject.org that hopefully will make it more clear how to request help.

**Closed by stevepiercy** 2017-03-26 21:43 UTC
