### ISSUE TITLE
[docs] The wsgi script in the apache mod_wsgi tutorial

### ISSUE THREAD

**Issue by bassio** [Pylons/pyramid#395] opened 2012-01-08 04:12 UTC
I successfully deployed on apache, mod_python.
http://docs.pylonsproject.org/projects/pyramid/en/1.0-branch/tutorials/modwsgi/index.html

but the wsgi script in the docs:
    from pyramid.paster import get_app
    application = get_app('/Users/chrism/modwsgi/env/myapp/production.ini', 'main')

failed to load the site,

so I had to prepend:

    import site
    site.addsitedir('/home/ahmed/dev/pyrenv/lib/python2.6/site-packages')

The addsitedir properly adds your site packages dir properly,
including following down all *.pth files etc. 

After that it worked as expected. I am not sure if this is the case for everyone, but perhaps consider adding it to the tutorial.

**Comment by stevepiercy** [comment] 2016-04-10 09:45
I think this has been resolved in #2438. I cannot reproduce the issue, so I'm closing it.

If it still remains, then please reopen the issue with explicit steps to reproduce.

**Closed by stevepiercy** 2016-04-10 09:45 UTC
Labels: docoverhaul, docs
