### ISSUE TITLE
pserve --reload fails with hupper under Windows

### ISSUE THREAD

**Issue by kalbermattenm** [Pylons/pyramid#2925] opened 2017-01-27 10:33 UTC
We ran into an issue using Pyramid 1.8.x with Python 2.7 (32-bits) under Windows 7.

After installing Pyramid (which worked) and initializing an alchemy project using `cookiecutter`, we tried to run `pserve` in reload mode, but that does not work (see here under). `pserve` only works in non-reload mode.

Actually, I do not really get what is happening. It sounds to me, like hupper would like to start two processes having the same pid, but this cannot be in Windows... (this is pure speculation...)

Do anyone have a clue about this ?

```
pserve.exe --reload development.ini
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\Lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\Lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\tmp\spch\venv\Scripts\pserve.exe\__main__.py", line 9, in <module>
  File "c:\tmp\spch\venv\lib\site-packages\pyramid\scripts\pserve.py", line 40, in main
    return command.run()
  File "c:\tmp\spch\venv\lib\site-packages\pyramid\scripts\pserve.py", line 205, in run
    verbose=self.args.verbose,
  File "c:\tmp\spch\venv\lib\site-packages\hupper\reloader.py", line 290, in start_reloader
    return reloader.run()
  File "c:\tmp\spch\venv\lib\site-packages\hupper\reloader.py", line 111, in run
    if not self._run_worker():
  File "c:\tmp\spch\venv\lib\site-packages\hupper\reloader.py", line 144, in _run_worker
    self.worker.start()
  File "c:\tmp\spch\venv\lib\site-packages\hupper\worker.py", line 149, in start
    send_fd(self.pipe, self.stdin_fd, self.pid)
  File "c:\tmp\spch\venv\lib\site-packages\hupper\ipc.py", line 35, in send_fd
    0, False, winapi.DUPLICATE_SAME_ACCESS,
  File "c:\tmp\spch\venv\lib\site-packages\hupper\winapi.py", line 123, in DuplicateHandle
    CheckError(ret, 'failed to duplicate handle')
  File "c:\tmp\spch\venv\lib\site-packages\hupper\winapi.py", line 112, in CheckError
    raise ctypes.WinError(ctypes.get_last_error(), msg)
WindowsError: [Error 87] failed to duplicate handle
```

**Comment by bertjwregeer** [comment] 2017-01-27 19:43
That is interesting, that error (87 from what I can find) is related to passing the wrong parameters to `DuplicateHandle`, which is weird.

We had to do some magic to get `hupper` working on Windows, sorry for the breakage, we will have to do some testing and look into it.

**Comment by mmerickel** [comment] 2017-01-28 02:57
Closing as a duplicate of https://github.com/Pylons/hupper/issues/12.

@kalbermattenm If you could, would you please try out my suggestions to diagnose things from that issue?

**Closed by mmerickel** 2017-01-28 02:57 UTC
