### ISSUE TITLE
PackageAssetSource package should be a string...

### ISSUE THREAD

**Issue by sbrunner** [Pylons/pyramid#1580] opened 2015-02-16 13:17 UTC
I'm using pyramid revision 620bdefbff81792fd047f273a234264ce3d0a764 with fa.jquery 0.9.5, and on this version I have this error:
```
Module weberror.evalexception:431 in respond         view
>>  app_iter = self.application(environ, detect_start_response)
Module fanstatic.publisher:219 in __call__         view
>>  return self.app(environ, start_response)
Module fanstatic.injector:54 in __call__         view
>>  response = request.get_response(self.app)
Module webob.request:1320 in send         view
>>  application, catch_exc_info=False)
Module webob.request:1284 in call_application         view
>>  app_iter = application(self.environ, start_response)
Module pyramid.router:242 in __call__         view
>>  response = self.invoke_subrequest(request, use_tweens=True)
Module pyramid.router:217 in invoke_subrequest         view
>>  response = handle_request(request)
Module pyramid_debugtoolbar.toolbar:166 in toolbar_tween         view
>>  return handler(request)
Module pyramid.tweens:21 in excview_tween         view
>>  response = handler(request)
Module pyramid_tm:95 in tm_tween         view
>>  reraise(*exc_info)
Module pyramid_tm:76 in tm_tween         view
>>  response = handler(request):0
Module pyramid.router:163 in handle_request         view
>>  response = view_callable(context, request)
Module pyramid.config.views:326 in attr_view         view
>>  return view(context, request)
Module pyramid.config.views:302 in predicate_wrapper         view
>>  return view(context, request)
Module pyramid.config.views:242 in _secured_view         view
>>  return view(context, request)
Module pyramid.config.views:352 in rendered_view         view
>>  result = view(context, request)
Module pyramid.config.views:488 in _class_view         view
>>  response = getattr(inst, attr)()
Module pyramid_formalchemy.views:119 in models         view
>>  return self.render(models=results)
Module pyramid_formalchemy.views:170 in render         view
>>  main = get_renderer('pyramid_formalchemy:templates/admin/master.pt').implementation(),
Module pyramid.renderers:153 in get_renderer         view
>>  return helper.renderer
Module pyramid.decorator:37 in __get__         view
>>  val = self.wrapped(inst)
Module pyramid.renderers:404 in renderer         view
>>  return factory(self)
Module pyramid_chameleon.zpt:10 in renderer_factory         view
>>  return renderer.template_renderer_factory(info, ZPTTemplateRenderer)
Module pyramid_chameleon.renderer:140 in template_renderer_factory         view
>>  return lookup(info)
Module pyramid_chameleon.renderer:115 in __call__         view
>>  filename)
Module pkg_resources:1127 in resource_filename         view
>>  self, resource_name
Module pyramid.config.assets:31 in get_resource_filename         view
>>  filename = overrides.get_filename(resource_name)
Module pyramid.config.assets:125 in get_filename         view
>>  result = source.get_filename(path)
Module pyramid.config.assets:224 in get_filename         view
>>  if pkg_resources.resource_exists(self.package, path):
Module pkg_resources:1116 in resource_exists         view
>>  return get_provider(package_or_requirement).has_resource(resource_name)
Module pkg_resources:396 in get_provider         view
>>  __import__(moduleOrReq)
TypeError: __import__() argument 1 must be string, not module
```

And I see that on those lines:
https://github.com/Pylons/pyramid/blob/master/pyramid/config/assets.py#L349-L351
Me convert the package mane into a module, and later SetupTools will do the same ...
https://bitbucket.org/pypa/setuptools/src/5277f79a423a9c88a3867f1b44dff3590d7c5145/pkg_resources/__init__.py?at=default#cl-395

Than if I change the `PackageAssetSource` building by:
`override_source = PackageAssetSource(to_package, override_prefix)`
it's working well :-)

Thanks in advance :-)

**Comment by mmerickel** [comment] 2015-02-16 15:51
Perhaps this code should just use `self.maybe_dotted`.

**Comment by sbrunner** [comment] 2015-02-16 16:42
In the `PackageAssetSource` class ?

**Comment by mmerickel** [comment] 2015-02-16 17:02
Sorry I think I see what's going on now. Is this a regression in setuptools that we cannot pass a package object into the `pkg_resources` methods?

**Comment by sbrunner** [comment] 2015-02-16 17:33
Not as I see I tested with the version 8.0 of SetupTools and I have the same issue, and when I have a look on the version 0.7 I see nearly the same code.

For me a better suspect is this commit:
https://github.com/Pylons/pyramid/commit/407b335ed9954c042377fd2e060c36edcd07cf60

**Comment by mmerickel** [comment] 2015-02-18 04:44
Can you please confirm that #1585 works for you?

**Comment by tseaver** [comment] 2015-02-19 22:10
Why does passing the `__name__` work, instead of the module?  `pkg_resources` has taken either one since Moses was a pup.

**Comment by mmerickel** [comment] 2015-02-19 22:20
@tseaver I thought so too. However, the asset code prior to me changing it was definitely using the **name**, and if you read the pkg_resources docs [1] I feel it's somewhat ambiguous.

> In the following methods, the package_or_requirement argument may be either a Python package/module name (e.g. foo.bar) or a Requirement instance. If it is a package or module name, the named module or package must be importable (i.e., be in a distribution or directory on sys.path), and the resource_name argument is interpreted relative to the named package.

I think a package object should be ok based on the fact that the wording is not "if it is a package **name** or module name". However:

```python
>>> import pkg_resources
>>> pkg_resources.resource_exists('pyramid, '__init__.py')
True
>>> import pyramid
>>> pkg_resources.resource_exists(pyramid, '__init__.py')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "XXX/eggs/setuptools-12.2-py2.7.egg/pkg_resources/__init__.py", line 1118, in resource_exists
    return get_provider(package_or_requirement).has_resource(resource_name)
  File "XXX/eggs/setuptools-12.2-py2.7.egg/pkg_resources/__init__.py", line 398, in get_provider
    __import__(moduleOrReq)
TypeError: __import__() argument 1 must be string, not module
>>>
```

[1] https://pythonhosted.org/setuptools/pkg_resources.html#basic-resource-access

**Comment by msabramo** [comment] 2015-02-20 00:16
#1587 is another fix for this issue that I coded before I knew #1585 existed. But I just added tests to it, so it's probably the better one to merge at this point.

**Comment by msabramo** [comment] 2015-02-20 04:00
Fixed via #1587.

**Comment by msabramo** [comment] 2015-02-20 04:00
@mmerickel: Want to close this?

**Comment by mmerickel** [comment] 2015-02-20 04:03
Yup, thank you.

**Closed by mmerickel** 2015-02-20 04:03 UTC
