### ISSUE TITLE
Content-Type: application/json shouldn't have a charset parameter.

### ISSUE THREAD

**Issue by gabisurita** [Pylons/pyramid#2860] opened 2016-12-08 23:15 UTC
Pyramid JSON renderer returns `Content-Type: application/json; charset=utf-8`, but according to [RFC 4627](https://tools.ietf.org/html/rfc4627), the `application/json` type doesn't have a charset parameter. It also describes why it's not needed. 

See http://stackoverflow.com/questions/13096259/can-charset-parameter-be-used-with-application-json-content-type-in-http-1-1

**Comment by mmerickel** [comment] 2016-12-08 23:49
What version of pyramid and webob are you using? This has been fixed but I can't remember if it's released yet (but I think it is).

**Comment by gabisurita** [comment] 2016-12-09 00:22
I'm using `pyramid-1.7.3` with `WebOb-1.6.3`. I think it's still unreleased. This was solved on #2706, right?

 Thank you and sorry for the repost.

**Comment by mmerickel** [comment] 2016-12-09 02:51
That PR you linked was reverted in favor of another solution as it was backward incompatible. I'm thinking of https://github.com/Pylons/webob/pull/197 which was released in webob 1.6.0.

Here is a test case that passes. Can you update it to reproduce your issue?

```
from pyramid.config import Configurator
from webtest import TestApp

def json_view(request):
    return {}

config = Configurator()
config.add_view(json_view, renderer='json')
app = config.make_wsgi_app()

testapp = TestApp(app)
r = testapp.get('/')
assert r.content_type == 'application/json'
```

**Comment by gabisurita** [comment] 2016-12-09 03:55
This test passes, but the following hello world app example doesn't:

```python
from wsgiref.simple_server import make_server
from pyramid.config import Configurator
from pyramid.view import view_config

@view_config(route_name='hello', renderer='json')
def hello_view(request):
    return {'hello': request.matchdict['name']}

def setup():
    config = Configurator()
    config.add_route('hello', '/hello/{name}')
    config.scan()
    app = config.make_wsgi_app()
    return app

if __name__ == '__main__':
    app = setup()
    server = make_server('0.0.0.0', 8080, app)
    server.serve_forever()
```

```http
$ curl -I localhost:8080/hello/aaa
HTTP/1.0 200 OK
Date: Fri, 09 Dec 2016 03:41:57 GMT
Server: WSGIServer/0.1 Python/2.7.12
Content-Type: application/json; charset=UTF-8
Content-Length: 16
```

Version sanity check:

```bash
$ pip show webob pyramid
Name: WebOb
Version: 1.6.3
Summary: WSGI request and response object
Home-page: http://webob.org/
Author: Pylons Project
Author-email: ianb@colorstudy.com
License: MIT
Location: /usr/lib/python2.7/site-packages
Requires: 
---
Name: pyramid
Version: 1.7.3
Summary: The Pyramid Web Framework, a Pylons project
Home-page: https://trypyramid.com
Author: Chris McDonough, Agendaless Consulting
Author-email: pylons-discuss@googlegroups.com
License: BSD-derived (http://www.repoze.org/LICENSE.txt)
Location: /usr/lib/python2.7/site-packages/pyramid-1.7.3-py2.7.egg
Requires: setuptools, WebOb, repoze.lru, zope.interface, zope.deprecation, venusian, translationstring, PasteDeploy

```

**Comment by gabisurita** [comment] 2016-12-09 04:17
If we test `request.headers['Content-Type']` instead of `request.content_type`, the following test doesn't pass:

```
from pyramid.config import Configurator
from webtest import TestApp

def json_view(request):
    return {}

config = Configurator()
config.add_view(json_view, renderer='json')
app = config.make_wsgi_app()

testapp = TestApp(app)
r = testapp.get('/')
assert r.headers['Content-Type'] == 'application/json'
```

**Comment by mmerickel** [comment] 2016-12-09 05:04
Upgrading to webob 1.7.0rc1 fixes this, however it also emits a `RuntimeWarning` so pyramid is probably doing something a little bit wrong here.

**Comment by bertjwregeer** [comment] 2016-12-09 17:40
Pyramid changes from `text/html; charset=utf-8` to setting `content_type` to `application/json` the warning you will be getting here is that WebOb has explicitly removed the `charset`.

In the future WebOb will remove all `content_type_parameters` when setting the `content_type`.

Pyramid isn't doing anything wrong, WebOb is warning about changed behaviour that a user may not be expecting.

**Comment by mmerickel** [comment] 2016-12-09 17:45
Is there a way for pyramid to avoid this warning in the update? Obviously people are going to open more bugs in our tracker if every `renderer='json'` view they have starts emitting a `RuntimeWarning`.

**Comment by bertjwregeer** [comment] 2016-12-09 17:50
```
res.charset = None
res.content_type = 'application/json'
```

Although it sounds like I should modify it instead to be a DeprecationWarning and that won't be shown by default...

**Comment by bertjwregeer** [comment] 2016-12-09 17:52
```
res.headers['Content-Type'] = 'application/json'
```

Bypasses all of it, and does the right thing, and no warning will be emitted. It's because of the "magic" that `res.content_type` does, which is bad API.

**Comment by mmerickel** [comment] 2016-12-12 07:07
I'm trying to decide if it's worth just setting the header directly. Thoughts?

**Comment by bertjwregeer** [comment] 2016-12-12 16:43
With the pinning of 1.7.0 in the `has_body` ticket there is no need for it.

**Closed** 2016-12-12 16:51 UTC
Labels: blocked-external-lib, bugs
