### ISSUE TITLE
BaseRequest.authorization raises uncatchable ValueError for malformed header

### ISSUE THREAD

**Issue by Kobnar** [Pylons/pyramid#2657] opened 2016-06-27 20:18 UTC
As part of my application's auth system, I need to get the values in `request.authorization`. While writing some basic tests for my app, I experimented with incorrectly formatted authorization headers. To my surprise, there is no simple way of dealing with a poorly supplied header from the client.

To some degree this looks like an upstream issue with WebOb (see [#231](https://github.com/Pylons/webob/issues/231)). Their `parse_auth` function attempts to split the header's string, but it offers no exception handling for strings that do not comply the standard. This results in a `ValueError` getting thrown whenever `parse_auth` is called for a malformed string.

It looks like a Pylons project member (rightly) doesn't like the idea of WebOb failing quietly, and I can see how it would be a trivial exception to catch if your working with WebOb itself. The problem is that `request.authorization` is handled way before my own app logic is called. The associated `ValueError` therefore raises an unhanded exception that results in a `501 Server Error` instead of a `400 Bad Request` - as one would expect.

I'd be happy to go at this. Any guidance before I dig in?

**Comment by Kobnar** [comment] 2016-06-27 20:22
### Examples

**Valid header:**
`authorization: Key a48f684882d498b4408e2a725d4e2e5f7532dc0642f8594516dd84c5`

**Invalid header:**
`authorization: a48f684882d498b4408e2a725d4e2e5f7532dc0642f8594516dd84c5`

The former should work fine, and the latter should raise a `400 Bad Request`.

**Comment by mmerickel** [comment] 2016-06-27 20:22
This is a duplicate of https://github.com/Pylons/webob/issues/231.

**Comment by Kobnar** [comment] 2016-06-27 20:23
Sorry. I'll check that out.

**Comment by Kobnar** [comment] 2016-06-27 20:23
Okay, I'll fiddle over there.

**Closed by mmerickel** 2016-06-27 20:22 UTC
