### ISSUE TITLE
UnicodeDecodeError on request.localizer with bogus GET params

### ISSUE THREAD

**Issue by marcinkuzminski** [Pylons/pyramid#3399] opened 2018-10-22 19:27 UTC
## Bug Report

**Describe the bug**
During some automated testing we discovered that there's potentially unexpected behaviour on requesting `request.localizer`

**To Reproduce**
1. Go to example url: http://server.com/demo?param=%f6%22%20onmouseover%3dveA2(9352)%20//
2. having such method:
```
def add_localizer(event):
    request = event.request
    localizer = request.localizer

    def auto_translate(*args, **kwargs):
        return localizer.translate(tsf(*args, **kwargs))

    request.translate = auto_translate
    request.plularize = localizer.pluralize

config.add_subscriber('rhodecode.subscribers.add_localizer',
                          'pyramid.events.NewRequest')
```

3. See error:

```
Traceback (most recent call last):
  File "/nix/store/5bc5w54x8hi5p74g3carpmb5caidxhj0-python2.7-pyramid-1.9.2/lib/python2.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/nix/store/5bc5w54x8hi5p74g3carpmb5caidxhj0-python2.7-pyramid-1.9.2/lib/python2.7/site-packages/pyramid/router.py", line 77, in handle_request
    has_listeners and notify(NewRequest(request))
  File "/nix/store/5bc5w54x8hi5p74g3carpmb5caidxhj0-python2.7-pyramid-1.9.2/lib/python2.7/site-packages/pyramid/registry.py", line 110, in notify
    [ _ for _ in self.subscribers(events, None) ]
  File "/nix/store/3hv873zjqqmq0czkrvp51lzz5i7xbs6a-python2.7-zope.interface-4.5.0/lib/python2.7/site-packages/zope/interface/registry.py", line 442, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/nix/store/3hv873zjqqmq0czkrvp51lzz5i7xbs6a-python2.7-zope.interface-4.5.0/lib/python2.7/site-packages/zope/interface/adapter.py", line 607, in subscribers
    subscription(*objects)
  File "/nix/store/5bc5w54x8hi5p74g3carpmb5caidxhj0-python2.7-pyramid-1.9.2/lib/python2.7/site-packages/pyramid/config/adapters.py", line 103, in derived_subscriber
    return subscriber(arg[0])
  File "/mnt/hgfs/marcink-shared/workspace/rhodecode-enterprise-ee/rhodecode/subscribers.py", line 64, in add_localizer
    localizer = request.localizer
  File "/nix/store/5bc5w54x8hi5p74g3carpmb5caidxhj0-python2.7-pyramid-1.9.2/lib/python2.7/site-packages/pyramid/decorator.py", line 42, in __get__
    val = self.wrapped(inst)
  File "/nix/store/5bc5w54x8hi5p74g3carpmb5caidxhj0-python2.7-pyramid-1.9.2/lib/python2.7/site-packages/pyramid/i18n.py", line 379, in localizer
    current_locale_name = self.locale_name
  File "/nix/store/5bc5w54x8hi5p74g3carpmb5caidxhj0-python2.7-pyramid-1.9.2/lib/python2.7/site-packages/pyramid/decorator.py", line 42, in __get__
    val = self.wrapped(inst)
  File "/nix/store/5bc5w54x8hi5p74g3carpmb5caidxhj0-python2.7-pyramid-1.9.2/lib/python2.7/site-packages/pyramid/i18n.py", line 394, in locale_name
    locale_name = negotiate_locale_name(self)
  File "/nix/store/5bc5w54x8hi5p74g3carpmb5caidxhj0-python2.7-pyramid-1.9.2/lib/python2.7/site-packages/pyramid/i18n.py", line 154, in negotiate_locale_name
    locale_name = negotiator(request)
  File "/nix/store/5bc5w54x8hi5p74g3carpmb5caidxhj0-python2.7-pyramid-1.9.2/lib/python2.7/site-packages/pyramid/i18n.py", line 140, in default_locale_negotiator
    locale_name = request.params.get(name)
  File "/nix/store/g7x7glw6m6gh255616s6f0xnkxb65ggf-python2.7-webob-1.7.4/lib/python2.7/site-packages/webob/request.py", line 851, in params
    params = NestedMultiDict(self.GET, self.POST)
  File "/nix/store/g7x7glw6m6gh255616s6f0xnkxb65ggf-python2.7-webob-1.7.4/lib/python2.7/site-packages/webob/request.py", line 833, in GET
    vars = GetDict(data, env)
  File "/nix/store/g7x7glw6m6gh255616s6f0xnkxb65ggf-python2.7-webob-1.7.4/lib/python2.7/site-packages/webob/multidict.py", line 287, in __init__
    MultiDict.__init__(self, data)
  File "/nix/store/g7x7glw6m6gh255616s6f0xnkxb65ggf-python2.7-webob-1.7.4/lib/python2.7/site-packages/webob/multidict.py", line 38, in __init__
    items = list(args[0])
  File "/nix/store/g7x7glw6m6gh255616s6f0xnkxb65ggf-python2.7-webob-1.7.4/lib/python2.7/site-packages/webob/compat.py", line 126, in parse_qsl_text
    yield (x.decode(encoding), y.decode(encoding))
  File "/nix/store/fb993ma5m3y1hs95gay44j8mjjq5qlkl-python-2.7.15/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 0: invalid start byte
```

**Expected behavior**
Passing bogus GET param shouldn't affect obtaining a localizer. instead, i would expect just failing on getting the GET param

**Comment by mmerickel** [comment] 2018-10-24 02:43
This isn't directly related to `request.localizer`, you can just replace it with one that doesn't use `request.params`. This issue is really just a duplicate of https://github.com/Pylons/webob/issues/161.

My best recommendation right now is to look at something like https://github.com/pypa/warehouse/blob/b278f61bf749e2f857116bbcce9f45443f9585d8/warehouse/sanity.py for sanitizing requests before they make it into the app.

**Closed by mmerickel** 2018-10-24 02:43 UTC

**Comment by marcinkuzminski** [comment] 2018-10-24 09:55
Thanks for the explanation, can you point me to direction how one can use a custom localizer?

I'll look at the sanity tween, this looks like a good solution as well.

**Comment by marcinkuzminski** [comment] 2018-10-24 10:30
Actually, the proposed solution that `warehouse` is using is much better. I came to this conclusion after doing some testing, and it seems like a global right approach instead of patching in many places.

Thanks again for a pointer to this!

**Comment by mmerickel** [comment] 2018-10-24 16:19
@marcinkuzminski just for reference https://docs.pylonsproject.org/projects/pyramid/en/1.9-branch/narr/i18n.html#locale-negotiators
