### ISSUE TITLE
In docs on narrow window, “Edit me on GitHub” band suddenly scales up

### ISSUE THREAD

**Issue by Anaphory** [Pylons/pyramid#2756] opened 2016-08-27 08:44 UTC
Browsing the docs with a firefox browser window half my screen size, I saw the “Edit me on GitHub” band that's normally some hundred pixels large in the top right corner of the screen scale up to window width×window width, filling the whole top part of the docs, when the browser window was less wide than about 750px (as seen below).
![githubband](https://cloud.githubusercontent.com/assets/1579723/18026318/5779e02e-6c3a-11e6-91a3-1ac09c83d46b.png)

**Comment by stevepiercy** [comment] 2016-08-27 09:08
Closing as duplicate of #2365.

**Closed by stevepiercy** 2016-08-27 09:08 UTC
