### ISSUE TITLE
AttributeError in `__acl__` property is silently discarded.

### ISSUE THREAD

**Issue by JocelynDelalande** [Pylons/pyramid#3398] opened 2018-10-19 17:05 UTC
**Describe the bug**

If `__acl__` is implemented as a property (which seems common row-level permission), any AttributeError triggered inside the property will we shadowed by AttributeError catching here :+1: 

**To Reproduce**
1. Implement a __acl__ property on a Ressource that may raise an AttributeError

```python
class Myresource(object):
    @property
    def __acl__(self):
        raise AttributeError
```

When checking acl, pyramid will just skip the ACL without crashing.

**Expected behavior**

Crash with an AttributeError

**Possible fix**

Relevant code is here: 

https://github.com/Pylons/pyramid/blob/bda1306749c62ef4f11cfe567ed7d56c8ad94240/src/pyramid/authorization.py#L72-L76

Instead of a try/except on `AttributeError`, we could use `hasattr`.

**Comment by mmerickel** [comment] 2018-10-19 18:46
@JocelynDelalande thanks for the report. This is a duplicate of https://github.com/Pylons/pyramid/issues/735 and was fixed to allow `__acl__` to be defined as a function instead of a property. As far as changing to `hasattr` this doesn't actually fix anything because python actually executes the property when you call `hasattr` which would bubble up any `AttributeError` raised.

Closing this as a duplicate but let me know if you disagree.

**Closed by mmerickel** 2018-10-19 18:46 UTC

**Comment by JocelynDelalande** [comment] 2018-10-20 09:03
Sorry, I searched the bug tracker but missed it.
