### ISSUE TITLE
TypeError raised when inspecting cyfunction

### ISSUE THREAD

**Issue by mdobrzanski** [Pylons/pyramid#3301] opened 2018-06-06 14:39 UTC
Function pyramid.compat.is_unbound_method uses function inspect.getargspec which doesn't handle cythonized functions. When I cythonize my modules with views a ConfigurationExecutionErrorr (<cyfunction error_view at 0x7fc88fd22890> is not a Python function) is raised on loading app.

```
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/__init__.py", line 1052, in make_wsgi_app
    self.commit()
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/__init__.py", line 684, in commit
    self.action_state.execute_actions(introspector=self.introspector)
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/__init__.py", line 1218, in execute_actions
    tb)
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/__init__.py", line 1212, in execute_actions
    callable(*args, **kw)
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/views.py", line 925, in register
    derived_view = derive_view(False, renderer)
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/views.py", line 972, in derive_view
extra_options=ovals,
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/views.py", line 1420, in _derive_view
    return self._apply_view_derivers(info)
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/views.py", line 1118, in _apply_view_derivers
    view = wraps_view(deriver)(view, info)
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/viewderivers.py", line 165, in inner
    wrapper_view = wrapper(view, info)
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/viewderivers.py", line 212, in mapped_view
mapped_view = mapper(**info.options)(view)
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/viewderivers.py", line 65, in __call__
    if is_unbound_method(view) and self.attr is None:
  File "/home/mike/envs/env1c/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/compat.py", line 269, in is_unbound_method
spec = getargspec(fn)
  File "/usr/lib/python2.7/inspect.py", line 816, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
pyramid.exceptions.ConfigurationExecutionError: <type 'exceptions.TypeError'>: <cyfunction error_view at 0x7fc88fd22890> is not a Python function
```
Here's a link to the line where exception is raised https://github.com/Pylons/pyramid/blob/77caaff93f3c7dc8d43d6375b06b05e2be6cf7d3/pyramid/compat.py#L273

**Comment by bertjwregeer** [comment] 2018-06-06 19:46
@mdobrzanski Could you provide a small sample project on Github that has a Cython setup for views so that I can attempt to fix this?

**Comment by bertjwregeer** [comment] 2018-06-06 19:47
Could you also see if this is an issue on Python 3 as well? Since there is a lot of changes that went into Python 3.

**Comment by mdobrzanski** [comment] 2018-06-08 14:02
```
virtualenv ./envs/env
virtualenv ./envs/envc
git clone git@github.com:mdobrzanski/pylons_3301.git
source ./envs/env/bin/activate
pip install cython
cd pylons_3301
python setup.py bdist_egg
deactivate
source ../envs/envc/bin/activate
easy_install dist/myproject-0.0-py2.7-linux-x86_64.egg
```

Test import in python

```
python
>>> import myproject
>>> exit()

```
`pserve development.ini`


```
Traceback (most recent call last):
  File "/home/mike/envs/envc/bin/pserve", line 11, in <module>
    load_entry_point('pyramid==1.9.2', 'console_scripts', 'pserve')()
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/scripts/pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/plaster_pastedeploy-0.5-py2.7.egg/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/myproject-0.0-py2.7-linux-x86_64.egg/myproject/__init__.py", line 16, in main
    return config.make_wsgi_app()
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/__init__.py", line 1052, in make_wsgi_app
    self.commit()
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/__init__.py", line 684, in commit
    self.action_state.execute_actions(introspector=self.introspector)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/__init__.py", line 1218, in execute_actions
    tb)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/__init__.py", line 1212, in execute_actions
    callable(*args, **kw)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/views.py", line 925, in register
    derived_view = derive_view(False, renderer)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/views.py", line 972, in derive_view
    extra_options=ovals,
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/views.py", line 1420, in _derive_view
    return self._apply_view_derivers(info)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/config/views.py", line 1118, in _apply_view_derivers
    view = wraps_view(deriver)(view, info)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/viewderivers.py", line 165, in inner
    wrapper_view = wrapper(view, info)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/viewderivers.py", line 212, in mapped_view
    mapped_view = mapper(**info.options)(view)
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/viewderivers.py", line 65, in __call__
    if is_unbound_method(view) and self.attr is None:
  File "/home/mike/envs/envc/local/lib/python2.7/site-packages/pyramid-1.9.2-py2.7.egg/pyramid/compat.py", line 268, in is_unbound_method
    spec = getargspec(fn)
  File "/usr/lib/python2.7/inspect.py", line 816, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
pyramid.exceptions.ConfigurationExecutionError: <type 'exceptions.TypeError'>: <cyfunction error_view at 0x7ff707ec2350> is not a Python function
  in:
  Line 14 of file /home/mike/envs/envc/local/lib/python2.7/site-packages/myproject-0.0-py2.7-linux-x86_64.egg/myproject/__init__.py:
    config.add_view(views.error_view, context=HTTPError)
```

**Comment by mmerickel** [comment] 2018-06-08 14:06
https://cython.readthedocs.io/en/latest/src/userguide/limitations.html#inspect-support

I think we'd only consider trying to add support for cython in pyramid if someone put in the work to get our test suite running some cython examples to ensure compatibility.

**Comment by mdobrzanski** [comment] 2018-06-08 14:07
I looked into the code of Pyramid and I think changes would be to complicated. Probably it makes more sense to separate modules to keep Pyramid thins pure python and compile only additional stuff.

**Comment by bertjwregeer** [comment] 2018-06-08 16:05
@mdobrzanski I appreciate the reproducible example.

**Comment by mcdonc** [comment] 2018-07-05 14:34
I'll close this, @mdobrzanski ; if you have other ideas about how to do it, or you work on it, please reopen.

**Closed by mcdonc** 2018-07-05 14:34 UTC
